# Generated by Django 6.1.1 on 2026-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('course_program', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
