# Generated by Django 6.1.1 on 2026-10-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('block_location', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True)),
                ('room_no', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(default='Available', max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel')),
            ],
        ),
    ]
